# Generated by Django 4.2.6 on 2023-12-30 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(max_length=35, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Username'),
        ),
    ]
