# Generated by Django 4.2.6 on 2023-10-30 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
                ('operation_id', models.PositiveIntegerField(verbose_name='Id')),
                ('operation_description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.machine', verbose_name='Machine')),
            ],
        ),
    ]
