# Generated by Django 4.2.6 on 2023-12-09 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
                ('number_of_tools', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Tools')),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
            ],
            options={
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
                ('operation_id', models.PositiveIntegerField(verbose_name='Id')),
                ('operation_description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='OrderParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Order Number')),
                ('item_number', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Item Number')),
                ('part_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Part Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
                ('tool_length', models.FloatField(blank=True, null=True, verbose_name='Tool Length')),
                ('tool_diameter', models.FloatField(blank=True, null=True, verbose_name='Tool Diameter')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_app.machine', verbose_name='Machine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_app.operations', verbose_name='Operation')),
            ],
            options={
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.AddField(
            model_name='operations',
            name='part_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_app.orderparts', verbose_name='Part Order'),
        ),
    ]
