# Generated by Django 4.2.6 on 2023-11-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_app.operations', verbose_name='Operation'),
        ),
    ]
