# Generated by Django 4.2.6 on 2023-12-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderparts',
            name='part_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='operation_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Id'),
        ),
    ]
