# Generated by Django 4.2.6 on 2023-11-13 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0002_tool_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='number_of_tools',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Tools'),
        ),
    ]
