# Generated by Django 4.2.6 on 2023-11-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0003_machine_description_machine_number_of_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Tool Diameter'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Tool Length'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_app.machine', verbose_name='Machine'),
        ),
    ]
